name: Release Osquery Version to Webstite

on:
    workflow_dispatch:
        inputs:
            version:
                description: Osquery Release Version
                required: true
                type: string


jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3

            - name: generate json files
              run: ruby tools/new_release.rb "${{ github.event.inputs.version }}" .
