name: Release Osquery Version to Webstite

on:
    workflow_dispatch:
        inputs:
            version:
                description: Osquery Release Version
                required: true
                type: string

permissions:
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
              with:
                ref: source
                fetch-depth: 0

            - name: generate json files
              run: ruby tools/new_release.rb "${{ github.event.inputs.version }}" .

            - name: Git Commit
              run: |
                  git checkout -b release-"${{ github.event.inputs.version }}"
                  git add --all
                  git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m "Release ${{ github.event.inputs.version }}"

            - name: git push
              run: |
                git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
                git push --set-upstream origin release-"${{ github.event.inputs.version }}"
              #env:
              #  GH_TOKEN: ${{ github.token }}

            - name: Generate PR
              run: gh pr create --base source --fill --head release-"${{ github.event.inputs.version }}"
              env:
                GH_TOKEN: ${{ github.token }}

